name: TestPlugin
main: io.github.colemcginn.TestPlugin.TestPlugin
version: 1.0.0
author: colemcginn
commands:
  basic:
    description: This is a demo command.
    usage: /<command> 
    permission: basic
    permission-message: You don't have <permission>
  testplugin:
    permission: TestPlugin
permissions:
  basic:
    default: true
  TestPlugin:
    default: true