name: TestPlugin
main: io.github.colemcginn.TestPlugin.TestPlugin
version: 1.0.0
author: colemcginn
commands:
  testplugin:
    permission: TestPlugin
permissions:
  TestPlugin:
    default: true
  TestPlugin.reload: 
    default: true
  TestPlugin.block: 
    default: true
  TestPlugin.join: 
    default: true
  TestPlugin.firstjoin: 
    default: true